apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/chatbot

patches:
- path: patches/resources.yaml
- path: patches/external-secret.yaml

images:
- name: moyeobab/chatbot
  newName: 676267940634.dkr.ecr.ap-northeast-2.amazonaws.com/moyeobab/chatbot
  newTag: sha-a73d52be

configMapGenerator:
- literals:
  - LOG_LEVEL=info
  name: chatbot-config

generatorOptions:
  disableNameSuffixHash: true
