apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moyeobab

resources:
  - namespace.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - recommend/deployment.yaml
  - recommend/service.yaml
  - gateway/httproute.yaml
  - external-secrets/secret-store.yaml
  - external-secrets/backend-es.yaml
  - external-secrets/recommend-es.yaml
