apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  # --- Helm chart 소스 ---
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "*"
    # --- Helm values (ESO 설정) ---
    helm:
      valuesObject:
        replicaCount: 1
        webhook:
          create: false
        certController:
          create: false
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
