apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommend-dev
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord-deploy-dev: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord-deploy-dev: ""
    notifications.argoproj.io/subscribe.on-health-degraded.discord-deploy-dev: ""
spec:
  project: default
  source:
    repoURL: git@github.com:100-hours-a-week/13-team-project-cloud.git
    path: v3-kubernetes/k8s/overlays/dev/recommend
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: moyeobab
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
