apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 1  # AI 팀 코드 수정 전까지 비활성화
  template:
    spec:
      containers:
        - name: chatbot
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1536Mi
