apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhooks
spec:
  dataFrom:
    - find:
        path: /moyeobab/monitoring/prod/
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: ".*/(.*)"
            target: "$1"
