apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
spec:
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        path: /moyeobab/monitoring/prod/
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: ".*/(.*)"
            target: "$1"
