apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/chatbot

patches:
  - path: patches/resources.yaml
  - path: patches/external-secret.yaml

images:
  - name: moyeobab/chatbot
    newName: 676267940634.dkr.ecr.ap-northeast-2.amazonaws.com/moyeobab/chatbot
    newTag: sha-dcaf9d9f

configMapGenerator:
  - name: chatbot-config
    literals:
      - LOG_LEVEL=WARNING
      - OTLP_ENDPOINT=tempo.monitoring.svc.cluster.local:4317
      - OTEL_SERVICE_NAME=chatbot

generatorOptions:
  disableNameSuffixHash: true
