apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moyeobab

resources:
- ../../base

patches:
- path: patches/backend-resources.yaml
- path: patches/recommend-resources.yaml

# CI에서 kustomize edit set image 로 태그 주입
images:
- name: moyeobab/backend
  newName: 676267940634.dkr.ecr.ap-northeast-2.amazonaws.com/moyeobab/backend
  newTag: sha-45e11615
- name: moyeobab/recommend
  newName: 676267940634.dkr.ecr.ap-northeast-2.amazonaws.com/moyeobab/recommend
  newTag: sha-c774472a44a6bc8fa1b9f249f5e8d64c0682bfb0

configMapGenerator:
- literals:
  - SPRING_PROFILES_ACTIVE=dev
  - AI_RECOMMENDATION_BASE_URL=http://recommend.moyeobab.svc.cluster.local:8000/api/v1
  name: backend-config
- literals:
  - LOG_LEVEL=info
  - QDRANT_TIMEOUT=5.0
  - QDRANT_COLLECTION=meetup_requests
  - MODEL_DIR=models
  name: recommend-config
