apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chatbot-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-ssm
  target:
    name: chatbot-secret
  dataFrom:
    - find:
        path: MUST_BE_OVERRIDDEN_BY_OVERLAY
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: ".*/(.*)"
            target: "$1"
