name: Incident Report
description: 장애/인시던트 리포트
title: "[Cloud] "
labels: ["장애"]
body:
  - type: markdown
    attributes:
      value: |
        ## 인시던트 리포트
        장애 상황을 기록해주세요.

  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      options:
        - Critical (서비스 전체 중단)
        - High (주요 기능 장애)
        - Medium (일부 기능 장애)
        - Low (경미한 영향)
    validations:
      required: true

  - type: input
    id: start-time
    attributes:
      label: 발생 시간
      description: 장애 발생 시간
      placeholder: "YYYY-MM-DD HH:MM"
    validations:
      required: true

  - type: input
    id: end-time
    attributes:
      label: 복구 시간
      description: 장애 복구 시간 (진행 중이면 비워두세요)
      placeholder: "YYYY-MM-DD HH:MM"
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: 영향 범위
      description: 어떤 서비스/사용자에게 영향이 있었는지
      placeholder: |
        - 영향받은 서비스:
        - 영향받은 사용자 수:
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 장애 내용
      description: 무슨 일이 발생했는지 상세히
    validations:
      required: true

  - type: textarea
    id: root-cause
    attributes:
      label: 원인 분석
      description: 장애 원인 (파악된 경우)
    validations:
      required: false

  - type: textarea
    id: resolution
    attributes:
      label: 조치 내용
      description: 어떻게 해결했는지
    validations:
      required: false

  - type: textarea
    id: prevention
    attributes:
      label: 재발 방지 대책
      description: 향후 방지를 위한 조치
    validations:
      required: false
