name: Sprint Backlog
description: 스프린트 백로그 항목 생성
title: "[Backlog] "
labels: ["백로그"]
body:
  - type: markdown
    attributes:
      value: |
        ## 스프린트 과제
        과제 정보를 입력해주세요.

  - type: input
    id: task-title
    attributes:
      label: 과제명
      description: 과제의 제목을 입력해주세요
      placeholder: ex) AWS EC2 인스턴스 생성
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 과제 설명
      description: 과제에 대한 상세 설명
      placeholder: 이 과제에서 수행할 작업을 설명해주세요
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 완료 조건
      description: 이 과제가 완료되었다고 판단할 수 있는 조건
      placeholder: |
        - [ ] 조건 1
        - [ ] 조건 2
        - [ ] 조건 3
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 참고 자료
      description: 관련 링크나 문서 (선택사항)
      placeholder: |
        - 관련 문서 링크
        - 참고 자료
    validations:
      required: false
