name: Troubleshooting
description: 트러블슈팅 기록
title: "[Troubleshooting] "
body:
  - type: markdown
    attributes:
      value: |
        ## 트러블슈팅
        발생한 문제와 해결 과정을 기록해주세요.

  - type: input
    id: occurred-at
    attributes:
      label: 발생 일시
      description: 문제 발생 시간
      placeholder: "YYYY-MM-DD HH:MM"
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: 영향 범위
      description: 어떤 서비스/기능에 영향이 있었는지
      placeholder: |
        - 영향받은 서비스:
        - 영향받은 사용자:
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 환경 정보
      description: 재현/문제 발생 환경
      placeholder: |
        - OS/AMI:
        - 리전/계정:
        - Terraform 버전:
        - 모듈/컴포넌트:
    validations:
      required: false

  - type: textarea
    id: symptoms
    attributes:
      label: 증상
      description: 무엇이 어떻게 실패했는지
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 방법
      description: 재현 가능한 경우 단계 작성
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 에러 로그/메시지
      description: 관련 로그, 스택트레이스, 스크린샷
    validations:
      required: false

  - type: textarea
    id: root-cause
    attributes:
      label: 원인
      description: 원인 분석
    validations:
      required: false

  - type: textarea
    id: resolution
    attributes:
      label: 해결
      description: 해결 방법/조치 내용
    validations:
      required: false

  - type: textarea
    id: verification
    attributes:
      label: 검증
      description: 해결 후 확인한 방법
    validations:
      required: false

  - type: textarea
    id: prevention
    attributes:
      label: 재발 방지/후속 조치
      description: 문서/코드/설정 반영 계획
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 참고
      description: 관련 이슈/PR/문서 링크
    validations:
      required: false
