apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhooks
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-ssm
  target:
    name: alertmanager-discord-webhooks
  dataFrom:
    - find:
        path: MUST_BE_OVERRIDDEN_BY_OVERLAY
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: ".*/(.*)"
            target: "$1"
