apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recommend-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-ssm
  target:
    name: recommend-secret
  dataFrom:
    - find:
        path: /moyeobab/recommend/dev/
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: ".*/(.*)"
            target: "$1"
