apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/recommend
  - pdb.yaml

patches:
  - path: patches/resources.yaml
  - path: patches/external-secret.yaml
  - path: patches/scheduling.yaml

images:
  - name: moyeobab/recommend
    newName: 676267940634.dkr.ecr.ap-northeast-2.amazonaws.com/moyeobab/recommend
    newTag: sha-a73d52be

configMapGenerator:
  - name: recommend-config
    literals:
      - LOG_LEVEL=WARNING
      - QDRANT_TIMEOUT=5.0
      - QDRANT_COLLECTION=meetup_requests
      - OTLP_ENDPOINT=tempo.monitoring.svc.cluster.local:4317
      - OTEL_SERVICE_NAME=recommend

generatorOptions:
  disableNameSuffixHash: true
