apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/recommend
  - servicemonitor.yaml

patches:
  - path: patches/resources.yaml
  - path: patches/external-secret.yaml

images:
  - name: moyeobab/recommend
    newName: 676267940634.dkr.ecr.ap-northeast-2.amazonaws.com/moyeobab/recommend
    newTag: sha-8a6bb4ac

configMapGenerator:
  - name: recommend-config
    literals:
      - LOG_LEVEL=WARNING
      - QDRANT_TIMEOUT=5.0
      - QDRANT_COLLECTION=meetup_requests

generatorOptions:
  disableNameSuffixHash: true
