apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: recommend
spec:
  selector:
    matchLabels:
      app: recommend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
