apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    chart: aws-ebs-csi-driver
    targetRevision: "*"
    helm:
      valuesObject:
        controller:
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 128Mi
        node:
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 128Mi
        storageClasses:
          - name: ebs-gp3
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
            parameters:
              type: gp3
              fsType: ext4
            reclaimPolicy: Retain
            volumeBindingMode: WaitForFirstConsumer
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
