apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secrets-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:100-hours-a-week/13-team-project-cloud.git
    path: v3-kubernetes/k8s/overlays/prod/monitoring
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
