apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "*"
    helm:
      valuesObject:
        deployment:
          kind: DaemonSet
        service:
          type: NodePort
        ports:
          web:
            port: 8000
            exposedPort: 80
            nodePort: 30080
          websecure:
            expose:
              default: false
          traefik:
            port: 9000
            expose:
              default: true
            exposedPort: 9000
        api:
          dashboard: true
          insecure: true
        gateway:
          listeners:
            web:
              port: 8000
              protocol: HTTP
              namespacePolicy:
                from: Selector
                selector:
                  matchLabels:
                    kubernetes.io/metadata.name: moyeobab
        providers:
          kubernetesGateway:
            enabled: true
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
        tracing:
          otlp:
            grpc:
              endpoint: "tempo.monitoring.svc.cluster.local:4317"
              insecure: true
        additionalArguments:
          - "--tracing.serviceName=traefik"
          - "--tracing.addInternals=true"
          - "--tracing.otlp.grpc.endpoint=tempo.monitoring.svc.cluster.local:4317"
          - "--tracing.otlp.grpc.insecure=true"
        logs:
          general:
            level: INFO
          access:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
