apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-ssm
  target:
    name: backend-secret
  dataFrom:
    - find:
        path: /moyeobab/spring/dev/
        name:
          regexp: ".*"
